CREATE TABLE client
(
	id								INTEGER					GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name							VARCHAR(256)		NOT NULL UNIQUE,
	certificate				BLOB						NOT NULL
);

CREATE TABLE file
(
	virtual_path			VARCHAR(256)		NOT NULL PRIMARY KEY,
	real_path					VARCHAR(256)		NOT NULL,
	filename					VARCHAR(256)		NOT NULL,
	content_type			VARCHAR(256)		NOT NULL,
	md5_checksum			VARCHAR(32)			NOT NULL,
	sha256_checksum		VARCHAR(64)			NOT NULL,
	timestamp					TIMESTAMP				DEFAULT NOW NOT NULL,
	start_date				TIMESTAMP				NOT NULL,
	end_date					TIMESTAMP				NOT NULL,
	client_id					INTEGER					NOT NULL,
	FOREIGN KEY (client_id) REFERENCES client(id)
);
